# Generated by Django 6.0 on 2026-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/'),
        ),
    ]
